services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: vtuber-song-list_development
      POSTGRES_USER: loco
      POSTGRES_PASSWORD: loco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
