//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod channels;
pub mod comments;
pub mod favorites;
pub mod prelude;
pub mod song_diffs;
pub mod song_items;
pub mod users;
pub mod videos;
